{
  imports = [
    ./atuin.nix
    ./bash.nix
    ./bat.nix
    ./bottom.nix
    ./direnv.nix
    ./eza.nix
    ./fd.nix
    ./fish.nix
    ./fzf.nix
    ./git.nix
    ./glamour.nix
    ./helix.nix
    ./izrss.nix
    ./neovim.nix
    ./nushell.nix
    ./spicetify.nix
    ./starship.nix
    ./taskwarrior.nix
    ./television.nix
    ./yazi.nix
  ];
}
